version: "3"
services:
  samba:
    stop_grace_period: 1s
    image: dockurr/samba
    container_name: samba
    environment:
      USER: "samba"
      PASS: "secret"
      UID: 1000    # Optional, default 1000
      GID: 1000    # Optional, default 1000
    ports:
      - 445:445
    volumes:
      - ./samba-storage/:/storage
    restart: always
    networks:
      samba:
        ipv4_address: 203.0.112.2
        # nc -z localhost 445
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "445"]
      interval: 1s
      timeout: 1s
      retries: 30
  # redis-init:
  #   stop_grace_period: 1s
  #   image: ghcr.io/qtvhao/redis:main
  #   container_name: redis-init
  #   environment:
  #     - REDIS_PASSWORD=secret
  #     - REDIS_AOF_ENABLED=no
  #   volumes:
  #     - ./samba-storage/bitnami-redis-data:/bitnami/redis/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "-a", "secret", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 3
  #   depends_on:
  #     samba-client:
  #       condition: service_completed_successfully
  # redis-cli:
  #   stop_grace_period: 30s
  #   image: ghcr.io/qtvhao/redis:main
  #   container_name: redis-cli
  #   # entrypoint: /opt/bitnami/scripts/redis/entrypoint.sh
  #   # command: /opt/bitnami/scripts/redis/run.sh
  #   privileged: true
  #   entrypoint: /bin/sh
  #   command: |
  #     -c "set -xe;
  #     redis-cli -a secret -h redis save
  #     "
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - samba
  redis:
    # stop_grace_period: 1s
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    # entrypoint: /opt/bitnami/scripts/redis/entrypoint.sh
    # command: /opt/bitnami/scripts/redis/run.sh
    privileged: true
    entrypoint: /bin/bash
    command: |
      -c 'set -xe;
      mkdir -p /bitnami/redis/data/backup-service;
      smbclient //203.0.112.2/Data -U samba%secret -c "mkdir bitnami-redis-data-backup-service";
      mount -t cifs //203.0.112.2/Data/bitnami-redis-data-backup-service /bitnami/redis/data/backup-service -o username=samba,password=secret;
      bash redis-backup-service.sh
      '
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_AOF_ENABLED=no
    networks:
      samba:
        ipv4_address: 203.0.112.3
    depends_on:
      samba-client:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "secret", "ping"]
      interval: 1s
      timeout: 5s
      retries: 20
  samba-client:
    image: ghcr.io/qtvhao/samba-client:main
    container_name: samba-client
    network_mode: host
    entrypoint: /bin/sh
    privileged: true
    restart: "no"
    depends_on:
      samba:
        condition: service_healthy
    command: |
      -c "set -xe;
      mkdir -p /mnt/smb_share;
      smbclient //203.0.112.2/Data -U samba%secret -c 'mkdir test-pod';
      mount -t cifs //203.0.112.2/Data/test-pod /mnt/smb_share -o username=samba,password=secret;
      echo 'Hello, Samba!' > /mnt/smb_share/hello-$RANDOM.txt;
      smbclient //203.0.112.2/Data -U samba%secret -c 'get test-pod/hello-$RANDOM.txt /hello-$RANDOM.txt';
      cat /hello-${RANDOM}.txt;"
networks:
  samba:
    ipam:
      driver: default
      config:
        - subnet: 203.0.112.0/24
