apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/samba-samba: "true"
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - /opt/bitnami/scripts/redis/run.sh
          command:
            - /opt/bitnami/scripts/redis/entrypoint.sh
          env:
            - name: REDIS_PASSWORD
              value: secret
          image: bitnami/redis:latest
          name: redis
      restartPolicy: Always
