apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/samba-samba: "true"
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - -c
            - |-
              set -xe;
              mkdir -p /bitnami/redis/data;
              smbclient //203.0.112.2/Data -U samba%secret -c 'mkdir bitnami-redis-data';
              mount -t cifs //203.0.112.2/Data/bitnami-redis-data /bitnami/redis/data -o username=samba,password=secret;
              echo 'Hello, Samba!' > /bitnami/redis/data/hello-23139.txt;
              mkdir -p /bitnami/redis/data/appendonlydir;
              smbclient //203.0.112.2/Data -U samba%secret -c 'get bitnami-redis-data/hello-23139.txt /hello-23139.txt';
              /opt/bitnami/scripts/redis/entrypoint.sh /opt/bitnami/scripts/redis/run.sh
          command:
            - /bin/sh
          env:
            - name: REDIS_AOF_ENABLED
              value: "no"
            - name: REDIS_PASSWORD
              value: secret
          image: ghcr.io/qtvhao/redis:main
          name: redis
          securityContext:
            privileged: true
      restartPolicy: Always
