apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: samba
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: samba
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/samba-samba: "true"
        io.kompose.service: samba
    spec:
      containers:
        - env:
            - name: GID
              value: "1000"
            - name: PASS
              value: secret
            - name: UID
              value: "1000"
            - name: USER
              value: samba
          image: dockurr/samba
          name: samba
          ports:
            - containerPort: 445
              hostPort: 445
              protocol: TCP
          volumeMounts:
            - mountPath: /storage
              name: samba-claim0
      restartPolicy: Always
      volumes:
        - name: samba-claim0
          persistentVolumeClaim:
            claimName: samba-claim0
