apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.network/samba-default: "true"
    io.kompose.service: samba-client
  name: samba-client
spec:
  containers:
    - args:
        - -c
        - |-
          set -xe;
          mkdir -p /mnt/smb_share;
          mount -t cifs //10.43.165.27/Data /mnt/smb_share -o username=samba,password=secret;
          echo 'Hello, Samba!' > /mnt/smb_share/hello-12538.txt;
          smbclient //10.43.165.27/Data -U samba%secret -c 'get hello-12538.txt /hello-12538.txt';
          cat /hello-12538.txt;
      command:
        - /bin/sh
      image: ghcr.io/qtvhao/samba-client:main
      name: samba-client
      securityContext:
        privileged: true
  restartPolicy: Never
